apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-appset
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
            overlay: overlays/nginx/platform
          # - cluster: prod
          #   url: https://kubernetes.default.svc
          #   overlay: overlays/prod
  template:
    metadata:
      name: 'nginx-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/carlosalvessdev/gitops-argo-cd.git
        targetRevision: main
        path: '{{overlay}}'
      destination:
        server: '{{url}}'
        namespace: default
      syncPolicy:
        automated: {}
